In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
np1 = np.array([2,3,4])

In [4]:
np1.shape

(3,)

In [5]:
np1.dtype

dtype('int64')

In [6]:
mat1 = np.array([[1,2],[3,4]])
mat1

array([[1, 2],
       [3, 4]])

In [7]:
mat1[0][0]=7
mat1

array([[7, 2],
       [3, 4]])

In [8]:
mat1[0][0]="numpy"
mat1

ValueError: invalid literal for int() with base 10: 'numpy'

##### np.arange - (start,stop,step,dtype) start - included,stop -excluded

In [9]:
mat2 = np.arange(0,6,1)
mat2

array([0, 1, 2, 3, 4, 5])

In [10]:
mat2 = np.arange(3,9,3)
mat2

array([3, 6])

In [11]:
mat2 = np.arange(4)
mat2

array([0, 1, 2, 3])

In [12]:
mat2 = np.arange(3.4)
mat2

array([0., 1., 2., 3.])

In [13]:
mat2 = np.arange(2,8,3,dtype="float32")
mat2

array([2., 5.], dtype=float32)

##### np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
retstep - size of spacing between sample

In [14]:
mat3 = np.linspace(2,5,5)
mat3

array([2.  , 2.75, 3.5 , 4.25, 5.  ])

In [15]:
mat3 = np.linspace(2,5,5,retstep=True)
mat3

(array([2.  , 2.75, 3.5 , 4.25, 5.  ]), 0.75)

In [16]:
mat3 = np.linspace(2,5,5,endpoint=False)
mat3

array([2. , 2.6, 3.2, 3.8, 4.4])

In [17]:
mat3 = np.linspace(2,5,5,endpoint=False,retstep=True)
mat3

(array([2. , 2.6, 3.2, 3.8, 4.4]), 0.6)

In [18]:
mat3 = np.linspace([1,2],[3,4],5)
mat3

array([[1. , 2. ],
       [1.5, 2.5],
       [2. , 3. ],
       [2.5, 3.5],
       [3. , 4. ]])

In [19]:
mat3 = np.linspace([1,2],[3,4],5,axis=1)
mat3

array([[1. , 1.5, 2. , 2.5, 3. ],
       [2. , 2.5, 3. , 3.5, 4. ]])

In [20]:
mat3 = np.linspace([[1,2,3]],[[3,4,5]],5)
mat3

array([[[1. , 2. , 3. ]],

       [[1.5, 2.5, 3.5]],

       [[2. , 3. , 4. ]],

       [[2.5, 3.5, 4.5]],

       [[3. , 4. , 5. ]]])

In [21]:
mat3 = np.linspace([[1,2,3]],[[3,4,5]],5,axis=1)
mat3

array([[[1. , 2. , 3. ],
        [1.5, 2.5, 3.5],
        [2. , 3. , 4. ],
        [2.5, 3.5, 4.5],
        [3. , 4. , 5. ]]])

In [22]:
mat3 = np.linspace([[1,2,3]],[[3,4,5]],5,axis=2)
mat3

array([[[1. , 1.5, 2. , 2.5, 3. ],
        [2. , 2.5, 3. , 3.5, 4. ],
        [3. , 3.5, 4. , 4.5, 5. ]]])

In [23]:
mat3 = np.linspace([1,2],3,5)
mat3

array([[1.  , 2.  ],
       [1.5 , 2.25],
       [2.  , 2.5 ],
       [2.5 , 2.75],
       [3.  , 3.  ]])

##### np.random.rand(d0,d1,d2,..)

In [24]:
mat4 = np.random.rand(4)
mat4

array([0.12040377, 0.02496059, 0.04353135, 0.66225556])

In [25]:
mat4 = np.random.rand(3,3)
mat4

array([[0.46749996, 0.52714664, 0.19626507],
       [0.50254079, 0.89869761, 0.14857272],
       [0.05716027, 0.76283933, 0.51094212]])

##### numpy.random.randint(low, high=None, size=None, dtype=’l’)

In [26]:
mat5 = np.random.randint(2,5)
mat5

3

In [27]:
mat5 = np.random.randint(2,5,3)
mat5

array([4, 4, 2])

##### np.diag(a,k)   a - array like , k=0 -> main diagonal, k<0 -> elements below main diagonal, k>0 -> vice-versa

In [28]:
a = [1,2,3]
mat5 = np.diag(a,0)
mat5

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [29]:
mat5 = np.diag(a,1)
mat5

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [30]:
a = [[1,2,3],[4,5,6],[7,8,9]]
mat5 = np.diag(a,0)
mat5

array([1, 5, 9])

In [31]:
mat5 = np.diag(a,-1)
mat5

array([4, 8])

In [32]:
mat5 = np.diag(a,-2)
mat5

array([7])

##### numpy.zeros(shape, dtype = None, order = ‘C’) 

In [33]:
mat6 = np.zeros(2)
mat6

array([0., 0.])

In [34]:
mat6 = np.zeros(2,dtype=int)
mat6

array([0, 0])

In [35]:
mat6 = np.zeros([2,3],dtype=int)
mat6

array([[0, 0, 0],
       [0, 0, 0]])

##### slicing operation

In [36]:
mat7 = [[1,2,3,4],[4,3,2,1],[1,2,3,4],[4,3,2,1],[1,2,3,4]]
mat7

[[1, 2, 3, 4], [4, 3, 2, 1], [1, 2, 3, 4], [4, 3, 2, 1], [1, 2, 3, 4]]

In [37]:
mat7[0,3]

TypeError: list indices must be integers or slices, not tuple

In [38]:
mat7[0:3]

[[1, 2, 3, 4], [4, 3, 2, 1], [1, 2, 3, 4]]

In [39]:
mat7 = np.array(mat7)
mat7

array([[1, 2, 3, 4],
       [4, 3, 2, 1],
       [1, 2, 3, 4],
       [4, 3, 2, 1],
       [1, 2, 3, 4]])

In [40]:
mat7[0,3]

4

In [41]:
mat7[0:3,1]

array([2, 3, 2])

In [42]:
mat7[:,2]

array([3, 2, 3, 2, 3])

In [43]:
mat7[0:3,:]

array([[1, 2, 3, 4],
       [4, 3, 2, 1],
       [1, 2, 3, 4]])